# Adjust sources
RTL = timing.sv greyhound_sine_core.sv greyhound_sine_periph.v sine_table.sv rom_async.sv rom_sync.sv ../../../primitives/primitive_wrappers.v
TOP = greyhound_sine_periph

# Include base Makefile
include ../../../makefile.include
