# Adjust sources
RTL = timing.sv vga_framebuffer_periph.v vga_framebuffer_periph_core.sv ../../../primitives/primitive_wrappers.v
TOP = vga_framebuffer_periph

# Include base Makefile
include ../../../makefile.include
