# Adjust sources
RTL = shader_memory.sv synchronizer.sv tiny_shader_top.sv shader_execute.sv spi_receiver.sv timing.sv tiny_shader.v
TOP = tiny_shader

# Include base Makefile
include ../../../makefile.include
